
com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http


liferay.oauth.application.external.reference.codes= custom-batch-client-extension-generator-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready


server.port=58081